name: just_jwt
description: A JWT library for Dart.
version: 4.0.0
homepage: https://github.com/deftomat/JustJWT

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  crypto: '^3.0.3'
  pointycastle: '^3.7.3'
  rsa_pkcs: '^2.0.1'
  collection: '^1.17.2'

dev_dependencies:
  test: '^1.24.3'