name: just_jwt
description: A JWT library for Dart.
version: 1.0.0
author: Tomas Szabo <tomas.szabo@deftomat.com>
homepage: https://github.com/deftomat/JustJWT

environment:
  sdk: '>=1.16.0 <2.0.0'

dependencies:
  crypto: '^2.0.1'
  pointycastle: '^0.10.0'
  rsa_pkcs: '^0.1.2'

dev_dependencies:
  test: '^0.12.15'