name: just_jwt
description: A JWT library for Dart.
version: 3.0.0
author: Tomas Szabo <tomas.szabo@deftomat.com>
homepage: https://github.com/deftomat/JustJWT

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  crypto: '^3.0.1'
  pointycastle: '^3.1.3'
  rsa_pkcs: '^2.0.0'
  collection: '^1.15.0'

dev_dependencies:
  test: '^1.16.8'