name: just_jwt
description: A JWT library for Dart.
version: 2.0.0
author: Tomas Szabo <tomas.szabo@deftomat.com>
homepage: https://github.com/deftomat/JustJWT

environment:
  sdk: '>=2.0.0-dev <3.0.0'

dependencies:
  crypto: '^2.0.1'
  pointycastle:
    git: https://github.com/PointyCastle/pointycastle.git
  rsa_pkcs:
    git: https://github.com/amaurel/rsa_pkcs.git
  collection: '^1.14.11'

dev_dependencies:
  test: '^1.3.4'